language: emacs-lisp

cache:
  apt: true
  timeout: 604800
  directories:
    - "$HOME/emacs"
    - ".cask/"
    - "$HOME/.emacs.d/.cask"

matrix:
  fast_finish: true
  allow_failures:
    - env: EMACS_VERSION=git-snapshot

git:
  depth: 1

env:
  matrix:
    - EMACS_VERSION=25.1
    - EMACS_VERSION=25.2
    - EMACS_VERSION=25.3
    - EMACS_VERSION=26.1
    - EMACS_VERSION=git-snapshot
  global:
    - PATH="$HOME/bin:$HOME/.cask/bin:$HOME/.evm/bin:$PATH"

before_install:
  - git clone -q --depth=1 https://github.com/rejeep/evm.git $HOME/.evm
  - evm config path /tmp

install:
  - evm install emacs-$EMACS_VERSION-travis --use --skip
  - curl -fsSkL https://raw.github.com/cask/cask/master/go | python

before_script:
  - EMACS_MAJOR_VERSION="$(echo $EMACS_VERSION | cut -d '.' -f 1)"

script:
  - .ci/run-tests.sh

notifications:
  email: false
